### ISSUE TITLE
Compile Any Type

### ISSUE THREAD

**Issue by Raul-Larena** [yafred/asn1-tool#11]
Hello!
The compiler does not support ANY / ANY DEFINED BY. According to the specification it should be replaced by an open type.
Is there some compiler class in charge of handling open types or ANY?
I've been using the tool and looking at the code, but I didn't find anything. 
Thank you!

**Comment by yafred** [comment]
Hello,
Nope, I did not go further than what is in X.680

**Comment by Raul-Larena** [comment]
Ok
Thank you!
