### ISSUE TITLE
Add constraint checking

### ISSUE THREAD

**Issue by odiferousmint** [yafred/asn1-tool#13]
Hello.

I have no clue if you would still be working on this, but constraint checking would be nice. For example:

```
FooProtocol DEFINITIONS ::= BEGIN

  FooQuestion ::= SEQUENCE {
      trackingNumber INTEGER(0..199),
      question       IA5String
  }

END
```

Here the value for `trackingNumber` can only be an integer, and it must be between 0 and 199. Of course this is no Ada, so the usual bound checks would do.

What would we do if it fails though? I presume this would result in a runtime error, but we should be able to catch this error, so perhaps what it should do is throw a constraint error that one could somehow catch? Is it feasible or possible? I do not know Java enough to tell.

---

> This change constrains trackingNumbers to have a value between 0 and 199 inclusive, and questionNumbers to have a value between 10 and 20 inclusive. The size of the questions array can be between 0 and 10 elements, with the answers array between 1 and 10 elements. The anArray field is a fixed length 100 element array of integers that must be in the range 0 to 1000. The '...' extensibility marker means that the FooHistory message specification may have additional fields in future versions of the specification; systems compliant with one version should be able to receive and transmit transactions from a later version, though able to process only the fields specified in the earlier version. **Good ASN.1 compilers will generate (in C, C++, Java, etc.) source code that will automatically check that transactions fall within these constraints. Transactions that violate the constraints should not be accepted from, or presented to, the application. Constraint management in this layer significantly simplifies protocol specification because the applications will be protected from constraint violations, reducing risk and cost.**

From https://en.wikipedia.org/wiki/ASN.1#Example.

---

Look at how Erlang does it (this is the compiled `FooProtocol.erl`):

```erlang
dec_FooQuestion(Tlv, TagIn) ->
  %%-------------------------------------------------
  %% decode tag and length 
  %%-------------------------------------------------
  Tlv1 = match_tags(Tlv, TagIn),

  %%-------------------------------------------------
  %% attribute trackingNumber(1) with type INTEGER
  %%-------------------------------------------------
  [V1|Tlv2] = Tlv1, 
  Term1 = begin
            Val1 = decode_integer(V1, [2]),
            if 0 =< Val1, Val1 =< 199 ->
                Val1;
               true ->
                exit({error,{asn1,bad_range}})
            end
          end,
[...]
```

As we are decoding `FooQuestion`, when we reach `trackingNumber`, we are trying to decode the value as an integer, and if the value is less  than 0 or greater than 199, then it exits with the error: `{error,{asn1,bad_range}}`. It is pretty straightforward. We should have something like that.

I would hope that it is possible in Java, too. As I said, in case of a constraint failure due to a wrong value for `trackingNumber`, in Erlang it returns `{error, {asn1, bad_range}}`.

This is how you catch for such an error (though here we catch all errors) when you are doing the decoding in Erlang (user code):

```erlang
case 'FooProtocol':decode('FooProtocol', Bytes) of
  {ok, _FP}       -> ok;
  {error, Reason} -> exit({error, Reason})
end
```

Again, the above code catches all errors as-is, and exits with them, so it would exit with `{error, {asn1, bad_range}}`, but the important thing is that you could easily catch the above in particular by changing `{error, Reason}` to `{error, {asn1, bad_range}}` (or better yet, adding it above, since we do want to catch the rest, too).

For completeness' sake, that would look like (user code):

```erlang
case 'FooProtocol':decode('FooProtocol', Bytes) of
  {ok, _FP} -> ok;
  {error, {asn1, bad_range}} -> HANDLE_THE_BAD_RANGE_ERROR_HERE;
  {error, Reason} -> exit({error, Reason})
end
```

Just to demonstrate:

```
1> X = {'FooQuestion', 200, "foo"}.                  
{'FooQuestion',200,"foo"}
2> {ok, Bin} = 'FooProtocol':encode('FooQuestion', X).
{ok,<<48,9,2,2,0,200,22,3,102,111,111>>}
3> {ok, Q} = 'FooProtocol':decode('FooQuestion', Bin).
** exception error: no match of right hand side value 
                    {error,
                     {asn1,
                      {bad_range,
                       [{'FooProtocol',dec_FooQuestion,2,
                         [{file, "/tmp/erlang/FooProtocol.erl"},
                          {line,130}]},
                        {'FooProtocol',decode,2,
                         [{file, "/tmp/erlang/FooProtocol.erl"},
                          {line,56}]},
                        {erl_eval,do_apply,6,
                         [{file,"erl_eval.erl"},{line,689}]},
                        {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},
                        {shell,exprs,7,[{file,"shell.erl"},{line,686}]},
                        {shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},
                        {shell,eval_loop,3,
                         [{file,"shell.erl"},{line,627}]}]}}}
```

As we can see, attempting to decode it with the invalid value (`200`) results in error `{error,{asn1,bad_range}}`. This is something you can catch like I did in the code above. Something like this would be ideal in Java. It has to be thrown from the generated file so the user can catch it when using its decode method.

**Comment by odiferousmint** [comment]
Thoughts?

**Comment by yafred** [comment]
Hi,
No, I'm not working on it at the moment.

I would have to dig into the code to give you a meaningful though

Anyway, the constraint grammar is [understood ](https://github.com/yafred/asn1-tool/blob/master/grammar/src/main/antlr4/com/yafred/asn1/grammar/ASN.g4#L437) but the information does make its way to the [model](https://github.com/yafred/asn1-tool/tree/master/model/src/main/java/com/yafred/asn1/model). There is some work to be done here before the code generator can use the constraint.

As for the generated code, I remember I was hesitating between to options when it comes to validating the decoded data

Option 1: let the decoder create a java object (being as permissive as possible) and then use a validator on the object (when you test that you field trackingNumber matches the constraint

Option 2: let the decoder raise an exception if some constraint are violated

The good thing about Option 1 is that you could ASN.1 to define a data model with constraints (even if no encoding/decoding happens)

A quick search on internet seems to show that a Runtime exception may be better: https://www.oss.com/asn1/products/documentation/asn1_java_8.3/asn1java-runtime-errors-index.html

**Comment by odiferousmint** [comment]
Oh thank you, that is quite an useful information; for everyone who may want to take a shot at implementing it. Thank you a lot!

**Comment by odiferousmint** [comment]
For the record, I deemed your project the best for encoding and decoding ASN.1, and yes, I have tried to use OSS NOKALVA's products as well. Yours is very easy to use, and it actually works. The only missing feature I wish it had is constraint checking, really... well, among supporting more of ASN.1.

**Comment by odiferousmint** [comment]
For the record, I think your project is the best for encoding and decoding ASN.1, and yes, I have tried to use OSS NOKALVA's products as well. Yours is very easy to use, and it actually works. The only missing feature I wish it had is constraint checking, really... well, among supporting more of ASN.1.

**Comment by yafred** [comment]
Thanks for the nice feedback

I'll take a look at the constraints when I have a moment

**Comment by odiferousmint** [comment]
> Thanks for the nice feedback
> 
> I'll take a look at the constraints when I have a moment

Thank you! That would be amazing and really appreciated!

**Comment by odiferousmint** [comment]
Thank you! I have yet to test it myself. Any issues or missing features you know of that is related?

**Comment by odiferousmint** [comment]
I am also wondering what it is that could potentially be missing.

https://www.erlang.org/doc/apps/asn1/asn1_getting_started.html is a good place to start. I will experiment myself with it.

**Comment by yafred** [comment]
As far as I remember, most of what you mention should be already implemented for Java. You can try and open issues on specific items.

Parameterization is not in the scope 

Extending the tool in order to ouput code for another programming language should be possible, but it requires understanding how to write your own [generator](https://github.com/yafred/asn1-tool/tree/master/generator). I started with Golang recently (you can have a look but it is not available in the finished tool, only in the build and unit tests)

However, before being able to say that you can safely write your own code generator, I would need to review the whole code structure and write some documentation ... starting with how to build the tool.
