### ISSUE TITLE
Feature Request: decimal Values bigger than 4 byte

### ISSUE THREAD

**Issue by cobba83** [yafred/asn1-tool#14]
Hi,

first of all, thanks a lot for this very nice project.

One thing i'm missing at the moment is the possibilty to use decimal values bigger than 4 byte.

Are there any plans of yours to implement that?

Kind regards
Fabian

**Comment by yafred** [comment]
No .... but it can be the next thing I will look at (when time allows)

Are using this tool in a public project ? If yes can you drop a link ?

**Comment by cobba83** [comment]
No, i need it for a project at work.
