### ISSUE TITLE
Problem Hex String Encoder

### ISSUE THREAD

**Issue by Serfermor** [yafred/asn1-tool#25]
I'm trying to use the compiler to encode a DENM message (https://forge.etsi.org/rep/ITS/asn1/denm_en302637_3)
My code right now look like this.

public class CreateDENMMessage {

    public static void main(String[] args) {
        // Create an instance of DENM
        DENM denmMessage = new DENM();

        // Set Header Information (if required)
        ItsPduHeader header = new ItsPduHeader();
        header.setProtocolVersion(2);
        header.setMessageID(MessageID.DENM);
        header.setStationID(1280119804);
        // Set header attributes here
        denmMessage.setHeader(header);

        // Create a DecentralizedEnvironmentalNotificationMessage
        DecentralizedEnvironmentalNotificationMessage denm = new DecentralizedEnvironmentalNotificationMessage();

        ManagementContainer manage = new ManagementContainer();

        ActionID action = new ActionID();
        action.setOriginatingStationID(1280119804);
        action.setSequenceNumber(1);
        manage.setActionID(action);

        manage.setDetectionTime(622991125); //622991127886
        manage.setReferenceTime(622991129); //622991127890
        manage.setTermination(Termination.Enum.ISCANCELLATION);

        ReferencePosition refpos = new ReferencePosition();
        refpos.setLatitude(367474912);
        refpos.setLongitude(-45555876);

        PosConfidenceEllipse ellipse = new PosConfidenceEllipse();
        ellipse.setSemiMajorConfidence(400);
        ellipse.setSemiMinorConfidence(400);
        ellipse.setSemiMajorOrientation(0);
        refpos.setPositionConfidenceEllipse(ellipse);

        Altitude alti = new Altitude();
        alti.setAltitudeValue(10717);
        alti.setAltitudeConfidence(AltitudeConfidence.Enum.ALT_000_02);
        refpos.setAltitude(alti);

        manage.setEventPosition(refpos);
        manage.setRelevanceDistance(RelevanceDistance.Enum.LESSTHAN500M);
        manage.setRelevanceTrafficDirection(RelevanceTrafficDirection.Enum.ALLTRAFFICDIRECTIONS);
        manage.setValidityDuration(7);
        manage.setTransmissionInterval(500);
        manage.setStationType(15);
        
        denm.setManagement(manage);

        SituationContainer situ = new SituationContainer();

        situ.setInformationQuality(0);

        CauseCode event = new CauseCode();
        event.setCauseCode(CauseCodeType.ACCIDENT);
        event.setSubCauseCode(0);
        situ.setEventType(event);

        situ.setLinkedCause();
        situ.setEventHistory();

        denm.setSituation(situ);
        
        LocationContainer loca = new LocationContainer();

        Speed event_sp = new Speed();
        event_sp.setSpeedValue(0);
        event_sp.setSpeedConfidence(127);
        loca.setEventSpeed(event_sp);
        loca.setRoadType(null);

        Heading event_h = new Heading();
        event_h.setHeadingValue(0);
        event_h.setHeadingConfidence(127);
        loca.setEventPositionHeading(event_h);

        loca.setTraces();
        denm.setLocation(loca);

        // Add the DecentralizedEnvironmentalNotificationMessage to the DENM
        denmMessage.setDenm(denm);

        // Validate the DENM message (if required)
        try {
            //DENM.validate(denmMessage);
        } catch (Exception e) {
            // Handle validation errors
            e.printStackTrace();
        }

    // Encode a DENM
    ByteArrayOutputStream bufferOut = new ByteArrayOutputStream();
    BERWriter berWriter = new BERWriter(bufferOut);
    try{
        DENM.writePdu(denmMessage, berWriter);
        
    } catch (Exception e) {
        e.printStackTrace();
    }

    byte[] berEncoded = bufferOut.toByteArray();
        // Convert the byte array to a hex string
        String berHex = bytesToHex(berEncoded);
        System.out.println("Encoded DENM in BER hex: " + berHex);
        
        
 }
 
The compilation is error free but the hex string is not the expected, any idea why would I'm not getting the correct hex string? It can be tested on this website (https://www.marben-products.com/decoder-asn1-automotive/) 'decode from direct input' option.

The encoded hex string although it is not correct it can be decoded back to the original values defined in the script pasted.

Thanks in advance.

_Originally posted by @Serfermor in https://github.com/yafred/asn1-tool/issues/21#issuecomment-1766612530_

**Comment by yafred** [comment]
Can you paste what is expected and what you get ?

Why do you think it's a problem ? (remember BER encoding is not canonical ... meaning that you cannot compare values based on their encoded form)

**Comment by Serfermor** [comment]
I'm not sure what is the problem, I cannot tell what I exactly expect to get. I'm trying to get this hex string '02014C4D13FCC7A62689FE00009221A546A9C4886951AA94B8C21E06892B15C1901900001B07D160001C1F30F0008018000FC001F800' but to achieve this I would need to define the "reference and detection time" with the commented values (same line) but I'm not able since they surpass integer expected values.

What I'm getting is this hex string '308185A00C80010281010182044C4D13FCA175A04EA00980044C4D13FC810101810425221715820425221719830100A422800415E738E08104FD48DF5CA20B8002019081020190820100A307800229DD810101850103860100870107880201F489010FA10F800100A106800106810100A200A300A212A00680010081017FA10680010081017FA200' that is way over the expected size.

Although BER is not canonical when I decode this hex string on other tools I get either an error or the string gets cropped and the values are way different from the ones I defined in java.

Thanks again

**Comment by Serfermor** [comment]
I realized the problem is that DENM messages are supposed to be encoded using UPER defined in ITU-T X.691. 
Thank for your response I will close the incidence.
