### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by julian252** [yafred/asn1-tool#4]
Symbol 'CrlSeries' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'EccP256CurvePoint' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'EciesP256EncryptedKey' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'EncryptionKey' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'GeographicRegion' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'GroupLinkageValue' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'HashAlgorithm' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'HashedId3' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'HashedId8' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Hostname' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'IValue' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'LinkageValue' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Opaque' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Psid' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'PsidSsp' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'PsidSspRange' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'PublicEncryptionKey' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'PublicVerificationKey' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'SequenceOfHashedId3' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'SequenceOfPsidSsp' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'SequenceOfPsidSspRange' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'ServiceSpecificPermissions' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Signature' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'SubjectAssurance' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'SymmetricEncryptionKey' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'ThreeDLocation' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Time64' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Uint3' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Uint8' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Uint16' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'Uint32' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
Symbol 'ValidityPeriod' is imported in module 'IEEE1609dot2' from an undefined module 'IEEE1609dot2BaseTypes'
[line 76:24] Type 'Uint8' neither defined nor imported
[line 81:30] Type 'Opaque' neither defined nor imported
[line 84:30] Type 'Opaque' neither defined nor imported
[line 89:21] Type 'HashAlgorithm' neither defined nor imported
[line 92:21] Type 'Signature' neither defined nor imported
[line 96:21] Type 'HashedId8' neither defined nor imported
[line 113:28] Type 'Psid' neither defined nor imported
[line 114:28] Type 'Time64' neither defined nor imported
[line 115:28] Type 'Time64' neither defined nor imported
[line 116:28] Type 'ThreeDLocation' neither defined nor imported
[line 117:28] Type 'HashedId3' neither defined nor imported
[line 119:28] Type 'EncryptionKey' neither defined nor imported
[line 121:28] Type 'SequenceOfHashedId3' neither defined nor imported
[line 126:21] Type 'HashedId3' neither defined nor imported
[line 127:21] Type 'CrlSeries' neither defined nor imported
[line 173:31] Type 'HashedId8' neither defined nor imported
[line 173:31] Type 'HashedId8' neither defined nor imported
[line 175:24] Type 'HashedId8' neither defined nor imported
[line 180:24] Type 'HashedId8' neither defined nor imported
[line 185:28] Type 'EciesP256EncryptedKey' neither defined nor imported
[line 186:28] Type 'EciesP256EncryptedKey' neither defined nor imported
[line 197:21] Type 'Opaque' neither defined nor imported
[line 216:29] Type 'Uint8' neither defined nor imported
[line 220:29] Type 'Signature' neither defined nor imported
[line 246:29] Type 'HashedId8' neither defined nor imported
[line 247:29] Type 'HashAlgorithm' neither defined nor imported
[line 249:29] Type 'HashedId8' neither defined nor imported
[line 254:28] Type 'HashedId3' neither defined nor imported
[line 255:28] Type 'CrlSeries' neither defined nor imported
[line 256:28] Type 'ValidityPeriod' neither defined nor imported
[line 257:28] Type 'GeographicRegion' neither defined nor imported
[line 258:28] Type 'SubjectAssurance' neither defined nor imported
[line 259:28] Type 'SequenceOfPsidSsp' neither defined nor imported
[line 263:28] Type 'PublicEncryptionKey' neither defined nor imported
[line 273:29] Type 'Hostname' neither defined nor imported
[line 280:27] Type 'IValue' neither defined nor imported
[line 281:27] Type 'LinkageValue' neither defined nor imported
[line 282:27] Type 'GroupLinkageValue' neither defined nor imported
[line 298:21] Type 'SequenceOfPsidSspRange' neither defined nor imported
[line 304:29] Type 'PublicVerificationKey' neither defined nor imported
[line 305:29] Type 'EccP256CurvePoint' neither defined nor imported

[IEEE1609dot2.asn.zip](https://github.com/yafred/asn1-tool/files/2427099/IEEE1609dot2.asn.zip)

**Comment by yafred** [comment]
Yes, you are missing IEEE1609dot2BaseTypes
I have found it here: https://raw.githubusercontent.com/wwhyte-si/1609dot2-asn/master/1609dot2-base-types.asn

At the moment, you can only have one input file.
So concatenate  IEEE1609dot2 and IEEE1609dot2BaseTypes in the same file [IEEE1609dot2.zip](https://github.com/yafred/asn1-tool/files/2428506/IEEE1609dot2.zip)

Then it does not choke anymore: 
**java -jar asn1-tool.jar -f IEEE1609dot2.asn -p**  shows you what the tool understands
**java -jar asn1-tool.jar -f IEEE1609dot2.asn -jo out** generates the Java code

Note that the ASN.1 constraints are understood by the tool but there is no validation and no Java mapping for them

**Comment by yafred** [comment]
It's because your spec is far beyond ITU-T X.680 (08/2015) that this tool tries to support.

Actually, you spec is so advanced that it is not even valid on what is for me the reference site http://asn1-playground.oss.com/
