### ISSUE TITLE
Underscore(_) breaks dictionary parsing

### ISSUE THREAD

**Issue by jigish-shah** [yafred/asn1-tool#8]
Hi

I was trying to parse few dictionaries with this tool using JAR. Almost everything is successful but when any dictionary which contains (_) anywhere, ASNParser stops parsing and throws error.

Is there anyway to come out from this?

I've an attribute "defaultCallHandling_" in dictionary but parser stops on validation.

Below is a code which I use to validate & traversing dictionaries:

`CharStream charStream = CharStreams.fromFileName("f:/dicts/av1.asn");
			ASNLexer lexer = new ASNLexer(charStream);
			TokenStream tokens = new CommonTokenStream(lexer);
	        ASNParser parser = new ASNParser(tokens);
	        ParseTree tree = parser.specification();`

Thanks!

**Comment by yafred** [comment]
Yes it's normal
I stick to the [ITU X.680 specification 
](https://www.itu.int/ITU-T/studygroups/com17/languages/X.680-0207.pdf)

If you want to bend the rules, the allowed characters are defined in the ANTLR [grammar](https://github.com/yafred/asn1-tool/blob/85e64ad272816294c775568839f8158a4b929503/grammar/src/main/antlr4/com/yafred/asn1/grammar/ASN.g4#L910)

**Comment by jigish-shah** [comment]
cool... tks

I believe we need to stick with standard.. I'll ask to change dictionary format as per above mentioned standard.

ta
