### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by gnarea** [yafred/asn1-tool#9]
Hello,

This project seems to be actively maintained since 2018 but the README still says "Warning: This tool is in development". Is it really not recommended for production use yet?

I want to parse DER-encoded values with the following structure in my Kotlin library.

```
Relaynet-RAMF DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  RAMF ::= SEQUENCE       
  {
     recipient          VisibleString (SIZE(1..1000)),
     messageId          VisibleString (SIZE(1..256)), 
     creationTimeUtc    DATE-TIME,
     ttl                INTEGER (0..7776000), 
     payload            OCTET STRING
  }                                                     
END
```

Would you advise against using this library for this?

**Comment by yafred** [comment]
Hi,

**Comment by yafred** [comment]
Another thing, you can try https://github.com/yafred/asn1-playground to see if your specification does not scare my tool.

**Comment by gnarea** [comment]
Thanks for the prompt answer @yafred! Great, I'll try that tomorrow. I'll close this issue in the meantime since my question is now answered.
